#!/opt/rangal/apps/python/venv3/bin/python3
import pika
import argparse
from emailParser import parse_email_parts as mail_parse
from py2neo import Graph, Node, Relationship
import pprint
from os import listdir
from os.path import isfile, join

class Mail2Neo():
    def __init__(self, hostname='localhost',  path='.', push=False):
        self.host = hostname
        self.path = path
        self.push = push

    def write_mail_to_neo(self, parsed_mail, src=None):
        g = Graph(password='jy1met2')
        if src is not None:
            parsed_mail['x-src-param']=src
        pprint.pprint(parsed_mail)
        tx = g.begin()
        a = Node("Article", **parsed_mail)
        tx.create(a)
        tx.commit()

    def parse_mail(self, content):
        return mail_parse(content)

if __name__ == '__main__':

    p = Mail2Neo('localhost')
    file_parse = None

    with open('mail.samp') as f:
        file_contents_ = f.read()
        file_parse = p.parse_mail(file_contents_)
    
    p.write_mail_to_neo(file_parse, 'hope')
